[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
author = "Evaristo Rojas"
author-email = "evaristo@evaristorojas.com"
classifiers = [ "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)", ]
description-file = "README.md"
home-page = "https://github.com/devarops/okf"
module = "okf"
requires = [
]
requires-python=">=3.9"

[tool.mutmut]
paths_to_mutate = [ "okf/" ]
tests_dir = [ "tests/" ]
